#	Trabalho pratico 1 de Compiladores - CCF 355
#	Feito por Mateus Pinto da Silva, matricula 3489
#	Universidade Federal de Viçosa

all:
	flex lex.l && gcc lex.yy.c

run:
	./a.out

run1:
	./a.out < entrada_padrao.txt

run2:
	./a.out
