#	Trabalho pratico 1 de Compiladores - CCF 355
#	Feito por Mateus Pinto da Silva, matricula 3489
#	Universidade Federal de Viçosa

all:
	flex lex.l && gcc lex.yy.c

run:
	./a.out

run0:
	./a.out < input/entrada_padrao.txt

run1:
	./a.out < input/entrada_personalizada1.txt

run2:
	./a.out < input/entrada_personalizada2.txt
